# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# For syntax: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: Deploy Release

on:
  release:
    types:
      - published

jobs:
  run-test:
    name: Running Tests
    runs-on: ubuntu-latest
    environment: build_environment
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{env.PNPM_VERSION}}

      - name: Use Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Installing Dependencies
        run: pnpm install

      - name: Cleaning Build Directory
        run: pnpm run clean

      - name: Building Tests
        run: pnpm run build

      - name: Running Tests
        run: pnpm test

  publish-gpr:
    name: Building and Publishing to GitHub Packages
    needs: [run-test]
    runs-on: ubuntu-latest
    environment: build_environment
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{env.PNPM_VERSION}}

      - name: Use Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://npm.pkg.github.com/

      - name: Installing Dependencies
        run: pnpm install

      - name: Cleaning Build Directory
        run: pnpm run clean

      - name: Building project
        run: pnpm run build

      - name: Publishing to packages
        run: pnpm publish --no-git-checks --access restricted
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
