# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# For syntax: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: Deploy Release

on:
  release:
    types:
      - published

jobs:
  source-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.source-branch.outputs.branch }}
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Get Source Branch from GitHub API
        id: get-branch # Set step ID to reference outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          REPO="${{ github.repository }}"

          # Get commit SHA associated with the release tag
          COMMIT_SHA=$(gh api repos/$REPO/git/ref/tags/$RELEASE_TAG --jq '.object.sha')

          # Find the branch that contains this commit
          SOURCE_BRANCH=$(gh api repos/$REPO/branches --jq ".[] | select(.commit.sha == \"$COMMIT_SHA\") | .name")

          # Store as an output
          echo "branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT

  run-test:
    name: Running Tests
    needs: source-branch
    runs-on: ubuntu-latest
    environment: build_environment
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{env.PNPM_VERSION}}

      - name: Use Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Installing Dependencies
        run: pnpm install

      - name: Cleaning Build Directory
        run: pnpm run clean

      - name: Building Tests
        run: pnpm run build

      - name: Running Tests
        run: pnpm test

  publish-gpr:
    name: Building and Publishing to GitHub Packages
    needs: [source-branch, run-test]
    runs-on: ubuntu-latest
    environment: build_environment
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{env.PNPM_VERSION}}

      - name: Use Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://npm.pkg.github.com/

      - name: Installing Dependencies
        run: pnpm install

      - name: Cleaning Build Directory
        run: pnpm run clean

      - name: Building project
        run: pnpm run build

      - name: Publishing to packages
        run: pnpm publish --publish-branch ${{ needs.source-branch.outputs.branch }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
